/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fix3.BodyPanel;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author abrardewapratamabarus
 */
public class BodyPanel extends javax.swing.JFrame {
    private void kosongkan_form(){
        //NamaField.setEditable(true);
        NamaField.setText(null);
        JKCombo.setSelectedItem(this);
        TelponField.setText(null);
        EmailField.setText(null);
        RekField.setText(null);
        JlhDonasiField.setText(null);
        TujuanCombo.setSelectedItem(this);
        JenisCombo.setSelectedItem(this);
    }
    private void tampilkan_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama ");
        model.addColumn("Jenis Kelamin");
        model.addColumn("No Telpon");
        model.addColumn("Email");
        model.addColumn("Nomor Rekening");
        model.addColumn("Jumlah Donasi");
        model.addColumn("Tujuan Berbagi");
        model.addColumn("Jenis Pembayaran");
        try{
            String sql ="Select * from data_donatur";
            java.sql.Connection conn = (Connection)Konfig.configDB();
            java.sql.Statement stm= conn.createStatement();
            java.sql.ResultSet res= stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)});
            }
            TabelDonatur.setModel(model);
            
        }catch (SQLException e){
            System.out.println("Error : "+e.getMessage());
        }
    }
    /**
     * Creates new form BodyPanel
     */
    public BodyPanel() {
        initComponents();
        tampilkan_data();
        kosongkan_form();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        BodyPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        DonasuButton = new javax.swing.JButton();
        FAQButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        KeluarButton = new javax.swing.JButton();
        AppTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Donatur = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        Tentang = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        GambarPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Donasi = new javax.swing.JPanel();
        JudulForm = new javax.swing.JLabel();
        NamaForm = new javax.swing.JLabel();
        JkForm = new javax.swing.JLabel();
        TelponForm = new javax.swing.JLabel();
        EmailForm = new javax.swing.JLabel();
        RekForm = new javax.swing.JLabel();
        JlhDonasiForm = new javax.swing.JLabel();
        TujuanForm = new javax.swing.JLabel();
        JenisPembayaranForm = new javax.swing.JLabel();
        BerbagiButton = new javax.swing.JButton();
        NamaField = new javax.swing.JTextField();
        TelponField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        RekField = new javax.swing.JTextField();
        JlhDonasiField = new javax.swing.JTextField();
        TujuanCombo = new javax.swing.JComboBox<>();
        JenisCombo = new javax.swing.JComboBox<>();
        JKCombo = new javax.swing.JComboBox<>();
        HapusButton = new javax.swing.JButton();
        FAQ = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Tampil = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelDonatur = new javax.swing.JTable();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPanel.setBackground(new java.awt.Color(24, 164, 224));

        DonasuButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        DonasuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix3/GambarPanel/money.png"))); // NOI18N
        DonasuButton.setText("Donasi");
        DonasuButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DonasuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonasuButtonActionPerformed(evt);
            }
        });

        FAQButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        FAQButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix3/GambarPanel/communications.png"))); // NOI18N
        FAQButton.setText("FAQ");
        FAQButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        FAQButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FAQButtonActionPerformed(evt);
            }
        });

        HomeButton.setBackground(new java.awt.Color(211, 221, 230));
        HomeButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix3/GambarPanel/web.png"))); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        KeluarButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        KeluarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix3/GambarPanel/exit_icon-icons.com_70975.png"))); // NOI18N
        KeluarButton.setText("Keluar");
        KeluarButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        KeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarButtonActionPerformed(evt);
            }
        });

        AppTitle.setBackground(new java.awt.Color(250, 248, 240));
        AppTitle.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 255)));
        AppTitle.setToolTipText("");
        AppTitle.setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YUK BERBAGI");

        javax.swing.GroupLayout AppTitleLayout = new javax.swing.GroupLayout(AppTitle);
        AppTitle.setLayout(AppTitleLayout);
        AppTitleLayout.setHorizontalGroup(
            AppTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AppTitleLayout.setVerticalGroup(
            AppTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AppTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Donatur.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        Donatur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix3/GambarPanel/give.png"))); // NOI18N
        Donatur.setText("Donatur");
        Donatur.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Donatur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonaturActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix3/GambarPanel/miscellaneous.png"))); // NOI18N

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(KeluarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Donatur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FAQButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DonasuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AppTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AppTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(HomeButton)
                .addGap(18, 18, 18)
                .addComponent(DonasuButton)
                .addGap(18, 18, 18)
                .addComponent(FAQButton)
                .addGap(18, 18, 18)
                .addComponent(Donatur)
                .addGap(69, 69, 69)
                .addComponent(KeluarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        AppTitle.getAccessibleContext().setAccessibleName("");

        MainPanel.setBackground(new java.awt.Color(125, 201, 231));
        MainPanel.setLayout(new java.awt.CardLayout());

        Tentang.setBackground(new java.awt.Color(125, 201, 231));

        jLabel13.setFont(new java.awt.Font("Bauhaus 93", 1, 36)); // NOI18N
        jLabel13.setText("YUK BERBAGI");

        GambarPanel.setBackground(new java.awt.Color(243, 244, 235));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fix3/GambarPanel/Donasi.jpeg"))); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout GambarPanelLayout = new javax.swing.GroupLayout(GambarPanel);
        GambarPanel.setLayout(GambarPanelLayout);
        GambarPanelLayout.setHorizontalGroup(
            GambarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GambarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        GambarPanelLayout.setVerticalGroup(
            GambarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GambarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TentangLayout = new javax.swing.GroupLayout(Tentang);
        Tentang.setLayout(TentangLayout);
        TentangLayout.setHorizontalGroup(
            TentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TentangLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(GambarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TentangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(320, 320, 320))
        );
        TentangLayout.setVerticalGroup(
            TentangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TentangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GambarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        MainPanel.add(Tentang, "card4");

        Donasi.setBackground(new java.awt.Color(125, 201, 231));

        JudulForm.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        JudulForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JudulForm.setText("Silahkan Isi Form");

        NamaForm.setText("Nama:");

        JkForm.setText("Jenis Kelamin:");

        TelponForm.setText("No Telpon:");

        EmailForm.setText("Email:");

        RekForm.setText("No Rekening:");

        JlhDonasiForm.setText("Jumlah Donasi:");

        TujuanForm.setText("Tujuan Berbagi:");

        JenisPembayaranForm.setText("Jenis Pembayaran:");

        BerbagiButton.setText("Berbagi");
        BerbagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BerbagiButtonActionPerformed(evt);
            }
        });

        TelponField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelponFieldActionPerformed(evt);
            }
        });

        TujuanCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sedekah", "Zakat", "Duafa" }));
        TujuanCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TujuanComboActionPerformed(evt);
            }
        });

        JenisCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gopay(0812451141214)", "Paypal(0241908210448)", "Transfer(1241253983593)", "Indomaret", " " }));

        JKCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki laki", "Perempuan" }));

        HapusButton.setText("Hapus");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DonasiLayout = new javax.swing.GroupLayout(Donasi);
        Donasi.setLayout(DonasiLayout);
        DonasiLayout.setHorizontalGroup(
            DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonasiLayout.createSequentialGroup()
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DonasiLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DonasiLayout.createSequentialGroup()
                                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BerbagiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NamaForm, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TelponForm, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EmailForm, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JkForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(RekForm)
                                    .addComponent(JlhDonasiForm)
                                    .addComponent(TujuanForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(DonasiLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(NamaField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                            .addComponent(TelponField)
                                            .addComponent(EmailField)
                                            .addComponent(RekField)
                                            .addComponent(JlhDonasiField)
                                            .addComponent(TujuanCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(JKCombo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(DonasiLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(HapusButton))))
                            .addGroup(DonasiLayout.createSequentialGroup()
                                .addComponent(JenisPembayaranForm)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JenisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(DonasiLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(JudulForm, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        DonasiLayout.setVerticalGroup(
            DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DonasiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(JudulForm)
                .addGap(18, 18, 18)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaForm)
                    .addComponent(NamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JkForm)
                    .addComponent(JKCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelponForm)
                    .addComponent(TelponField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailForm)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RekForm)
                    .addComponent(RekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlhDonasiForm)
                    .addComponent(JlhDonasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TujuanForm)
                    .addComponent(TujuanCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JenisPembayaranForm)
                    .addComponent(JenisCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(DonasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BerbagiButton)
                    .addComponent(HapusButton))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        MainPanel.add(Donasi, "card2");

        FAQ.setBackground(new java.awt.Color(125, 201, 231));

        jLabel12.setFont(new java.awt.Font("Bauhaus 93", 0, 24)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("FAQ");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Question:Apa itu Yuk Berbagi?                     \nAnswer :Yuk Berbagi adalah program tolong menolong kemanusiaanantar sesama. Dengan bergabung di Yuk Berbagi \nQuestion:Siapa saja yang bisa gabung Yuk Berbagi?\nAnswer:Semua orang bisa gabung Yuk Berbagi, baik yang pernah berdonasi maupun belum pernah berdonasi di Yuk \nQuestion:Bagaimana cara gabung Yuk Berbagi?\nAnswer:Download Aplikasi Yuk Berbagi di divice Anda,Klik \"DONASI SEKARANG\",lalu Daftar");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout FAQLayout = new javax.swing.GroupLayout(FAQ);
        FAQ.setLayout(FAQLayout);
        FAQLayout.setHorizontalGroup(
            FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(FAQLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        FAQLayout.setVerticalGroup(
            FAQLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FAQLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel12)
                .addGap(100, 100, 100)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        MainPanel.add(FAQ, "card3");

        Tampil.setBackground(new java.awt.Color(125, 201, 231));

        jPanel3.setBackground(new java.awt.Color(125, 201, 231));

        jLabel4.setFont(new java.awt.Font("Bauhaus 93", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DATA DONATUR");

        TabelDonatur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TabelDonatur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDonaturMouseClicked(evt);
            }
        });
        TabelDonatur.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                TabelDonaturVetoableChange(evt);
            }
        });
        jScrollPane3.setViewportView(TabelDonatur);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(287, 287, 287)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout TampilLayout = new javax.swing.GroupLayout(Tampil);
        Tampil.setLayout(TampilLayout);
        TampilLayout.setHorizontalGroup(
            TampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TampilLayout.setVerticalGroup(
            TampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MainPanel.add(Tampil, "card6");

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TelponFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelponFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelponFieldActionPerformed

    private void BerbagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BerbagiButtonActionPerformed
        // TODO add your handling code here:
        try{
            String sql= "INSERT INTO data_donatur VALUES ('"+NamaField.getText()+"','"+JKCombo.getSelectedItem()+"','"+TelponField.getText()+"','"+EmailField.getText()+"','"+RekField.getText()+"','"+JlhDonasiField.getText()+"','"+TujuanCombo.getSelectedItem()+"','"+JenisCombo.getSelectedItem()+"')";
            java.sql.Connection conn =(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
             JOptionPane.showMessageDialog(null,"Proses Simpan Data Berhasil! ");
             kosongkan_form();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_BerbagiButtonActionPerformed

    private void TabelDonaturVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_TabelDonaturVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TabelDonaturVetoableChange

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        try{
            String sql= "DELETE FROM data_donatur WHERE nama='"+NamaField.getText()+"'";
            java.sql.Connection conn =(Connection)Konfig.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
             JOptionPane.showMessageDialog(null,"Hapus Data Berhasil! ");
             kosongkan_form();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void TabelDonaturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDonaturMouseClicked
        // TODO add your handling code here:
        int baris= TabelDonatur.rowAtPoint(evt.getPoint());
        String nama= TabelDonatur.getValueAt(baris, 0).toString();
        NamaField.setText(nama);
        String Jk= TabelDonatur.getValueAt(baris, 1).toString();
        JKCombo.setSelectedItem(Jk);
        String telp= TabelDonatur.getValueAt(baris, 2).toString();
        TelponField.setText(telp);
        String email= TabelDonatur.getValueAt(baris, 3).toString();
        EmailField.setText(email);
        String rek= TabelDonatur.getValueAt(baris, 4).toString();
        RekField.setText(rek);
        String jlh= TabelDonatur.getValueAt(baris, 5).toString();
        JlhDonasiField.setText(jlh);
        String tujuan= TabelDonatur.getValueAt(baris, 6).toString();
        TujuanCombo.setSelectedItem(tujuan);
        String jenis= TabelDonatur.getValueAt(baris, 7).toString();
        JenisCombo.setSelectedItem(jenis);
    }//GEN-LAST:event_TabelDonaturMouseClicked

    private void TujuanComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TujuanComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TujuanComboActionPerformed

    private void DonaturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonaturActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(Tampil);
        MainPanel.repaint();
        MainPanel.revalidate();
        tampilkan_data();
    }//GEN-LAST:event_DonaturActionPerformed

    private void KeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_KeluarButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(Tentang);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void FAQButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FAQButtonActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(FAQ);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_FAQButtonActionPerformed

    private void DonasuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonasuButtonActionPerformed
        // TODO add your handling code here:
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();

        MainPanel.add(Donasi);
        MainPanel.repaint();
        MainPanel.revalidate();
    }//GEN-LAST:event_DonasuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BodyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BodyPanel().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AppTitle;
    private javax.swing.JButton BerbagiButton;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JPanel Donasi;
    private javax.swing.JButton DonasuButton;
    private javax.swing.JButton Donatur;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel EmailForm;
    private javax.swing.JPanel FAQ;
    private javax.swing.JButton FAQButton;
    private javax.swing.JPanel GambarPanel;
    private javax.swing.JButton HapusButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JComboBox<String> JKCombo;
    private javax.swing.JComboBox<String> JenisCombo;
    private javax.swing.JLabel JenisPembayaranForm;
    private javax.swing.JLabel JkForm;
    private javax.swing.JTextField JlhDonasiField;
    private javax.swing.JLabel JlhDonasiForm;
    private javax.swing.JLabel JudulForm;
    private javax.swing.JButton KeluarButton;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JTextField NamaField;
    private javax.swing.JLabel NamaForm;
    private javax.swing.JTextField RekField;
    private javax.swing.JLabel RekForm;
    private javax.swing.JTable TabelDonatur;
    private javax.swing.JPanel Tampil;
    private javax.swing.JTextField TelponField;
    private javax.swing.JLabel TelponForm;
    private javax.swing.JPanel Tentang;
    private javax.swing.JComboBox<String> TujuanCombo;
    private javax.swing.JLabel TujuanForm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
